name = "Nazir Hussain"
avatar = "images/nazir.jpg" # Avatar image. Default to "images/nazir.jpg".
bio = "Friends, my name is Nazir hussain and I am a Content writer. I like to share my knowledge with others, so I share my knowledge about SEO, Blogging, WordPress, Blogspot with others. How do you like our article, definitely tell in the comment box."
company = "gkgud"
location = "India"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"
