name = "Nazir Hussain"
avatar = "images/nazir.jpg" # Avatar image. Default to "images/nazir.jpg".
bio = "Content Developer, SEO Specialist."
company = "gkgud"
location = "India"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"
