email = "gkgud@outlook.com"
facebook = "GkGudP"
# github = "yourgithubusername"
# gitlab = "yourgitlabusername"
# linkedin = "yourlinkedinusername"
# stackoverflow = "yourstackoverflowuserid"
# twitter = "yourtwitterusername"
# weibo = "yourweibousername"
# zhihu = "yourzhihuusername"
# instagram = "yourinstagramusername"
# quora = "itechf"
# tumblr = "yourtumblrusername"
# reddit = "yourredditusername"
# telegram = "yourtelegramusername"
# qq = "yourqqnumber"
# dockerhub = "yourdockerhubusername"
# bitbucket = "yourbitbucketworkspaceid"
# medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
# bilibili = "yourbilibiliuserid"
youtube = "UCfgmG1A2Za-nU5R6rFv7q1g"
# discord = "yourdiscordinvitecode"
# discourse = "https://yourforum.tld"
# facebookgroup = "yourfacebookgroupname"
